# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/thor/digital_design2017/gcd_struct_Task4_Vivado2016/gcd_struct_Task4_Vivado2016.cache/wt [current_project]
set_property parent.project_path /home/thor/digital_design2017/gcd_struct_Task4_Vivado2016/gcd_struct_Task4_Vivado2016.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo /home/thor/digital_design2017/gcd_struct_Task4_Vivado2016/gcd_struct_Task4_Vivado2016.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/thor/digital_design2017/lab1/task2/debounce_entity.vhd
  /home/thor/digital_design2017/lab1/task4/comp.vhd
  /home/thor/digital_design2017/lab1/task2/debounce_synth.vhd
  /home/thor/digital_design2017/lab1/task4/gcd_struct.vhd
  /home/thor/digital_design2017/lab1/task2/gcd_top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/thor/digital_design2017/lab1/task2/Nexys4DDR_gcd.xdc
set_property used_in_implementation false [get_files /home/thor/digital_design2017/lab1/task2/Nexys4DDR_gcd.xdc]


synth_design -top gcd_sys -part xc7a100tcsg324-1


write_checkpoint -force -noxdef gcd_sys.dcp

catch { report_utilization -file gcd_sys_utilization_synth.rpt -pb gcd_sys_utilization_synth.pb }
